import type { Metadata } from 'next';
import './globals.css';
import { cn } from '../lib/utils';
import StoreProvider from '@/components/StoreProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <StoreProvider>
      <html lang="en">
        <head>
          <link
            href="https://fonts.cdnfonts.com/css/satoshi"
            rel="stylesheet"
          />
        </head>
        <body className={cn('font-sans')}>{children}</body>
      </html>
    </StoreProvider>
  );
};

export default RootLayout;
